---
title: "Multivariate Data Analysis"
author: "Juan Pablo Zaldivar && Enric Millán && Joel Solé"
date: "2023-05-11"
output: html_document
---

```{r setup, include=F, warnings=F, echo=F}

knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo=FALSE)

YlGnBu = c("#ffffd9", "#edf8b1", "#c7e9b4", "#7fcdbb", "#41b6c4", "#1d91c0", "#225ea8", "#253494", "#081d58")

source("plots.R")

library(dplyr)
library(plotly)
library(ggplot2)
```

# Exploratory data analysis

```{r}
glass <- read.csv2("glass.csv", header=TRUE, sep=",")
head(glass)
```

```{r}
# Transform features into numeric
features <- names(glass)[names(glass) != "Type"]
glass[features] <- lapply(glass[features], as.numeric)

# Transform label as categorical
glass$Type <- as.factor(glass$Type)
```

```{r}
unique(glass$Type)
```


```{r}
bar_plot <- plot_ly(data = glass, x = ~Type,
                    color = ~Type, colors = "YlGnBu") %>%
  add_histogram() %>%
  layout(title = "Count of Types in Glass Dataset",
         xaxis = list(title = "Type"), yaxis = list(title = "Count"))

bar_plot
```

```{r}
# Compute correlation matrix
corr_matrix <- cor(glass[, 1:9])

# Create a heatmap using Plotly
heatmap <- plot_ly(
  x = colnames(corr_matrix),
  y = colnames(corr_matrix),
  z = corr_matrix,
  type = "heatmap",
  colorscale = "YlGnBu"
)

# Add cell values to the heatmap
heatmap <- heatmap %>%
  add_annotations(
    x = rep(colnames(corr_matrix), each = length(colnames(corr_matrix))),
    y = rep(colnames(corr_matrix), length(colnames(corr_matrix))),
    text = round(corr_matrix, 2),
    showarrow = FALSE)

heatmap
```

```{r}
histogram_plots(glass, ncol(glass))
```


Ba and Fe are not very common elements.

```{r}
box_plots(glass, ncol(glass))
```


# Preprocesing

The row number 40 is a duplicate of the previous row.

```{r}
anyDuplicated(glass)
# glass <- glass[!duplicated(glass),]
```

## Data transformation

```{r}
num_features <- select_if(glass, is.numeric)

# Perform tipification (standardization)
tipified_data <- scale(num_features)

# Convert the tipified data back to a dataframe
tipified_df <- as.data.frame(tipified_data)

# Combine the tipified numerical features with the categorical variable
tipified_glass <- cbind(tipified_df, glass$Type)
colnames(tipified_glass)[ncol(tipified_glass)] <- "Type"

# Print the tipified dataset
print(tipified_glass)
```

```{r}
histogram_plots(tipified_glass, ncol(tipified_glass))
```


```{r}
library(forecast)

# Select the numerical features
num_features <- select_if(glass, is.numeric)

# Perform Box-Cox transformation
transformed_data <- lapply(num_features, function(feature) {
  lambda <- BoxCox.lambda(feature)
  if (lambda == 0) {
    log(feature + 1)
  } else {
    (feature^lambda - 1) / lambda
  }
})

# Convert the transformed data back to a dataframe
transformed_df <- as.data.frame(transformed_data)

# Combine the transformed numerical features with the categorical variable
transformed_glass <- cbind(transformed_df, glass$Type)
colnames(transformed_glass)[ncol(transformed_glass)] <- "Type"

# Print the transformed dataset
print(transformed_glass)
```

```{r}
histogram_plots(transformed_glass, ncol(transformed_glass))
```

## Missing values

```{r}
sum(is.na(glass))
```

## Outliers

```{r}
# Select the numerical features
glass_copy <- glass[, which(!(names(glass) %in% c('Ba', 'Fe')))]
num_features <- select_if(glass_copy, is.numeric)

# Detect outliers using the IQR method
outliers <- lapply(num_features, function(feature) {
  q1 <- quantile(feature, 0.25)
  q3 <- quantile(feature, 0.75)
  iqr <- q3 - q1
  lower_bound <- q1 - 1.5 * iqr
  upper_bound <- q3 + 1.5 * iqr
  outlier_rows <- which(feature < lower_bound | feature > upper_bound)
  outlier_rows
})

# Combine the outlier indexes
outlier_indexes <- unique(unlist(outliers))

# Drop the outlier rows from the "glass" dataframe
cleaned_glass <- glass[-outlier_indexes, ]
dim(cleaned_glass)
```

```{r}
histogram_plots(cleaned_glass, ncol(cleaned_glass))
```
















.

